name: Autograding Tests

on:
  push:
  workflow_dispatch:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Dependencies
      run: |
        npm install
        npx playwright install --with-deps chromium
        
    - name: Unit Tests
      id: unit-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Unit Tests'
        command: 'npm run test:unit'
        timeout: 10
        max-score: 3
        
    - name: Build Test
      id: build-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Build Test'
        command: 'npm run build'
        timeout: 10
        max-score: 2
        
    - name: App Integration Tests
      id: app-integration
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'App Integration Tests'
        command: 'npx playwright test tests/e2e/app.spec.ts'
        timeout: 10
        max-score: 3
        
    - name: Home Page Tests
      id: home-page
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Home Page Tests'
        command: 'npx playwright test tests/e2e/home.spec.ts'
        timeout: 10
        max-score: 2
        
    - name: Lobby Settings Tests
      id: lobby-settings
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Lobby Settings Tests'
        command: 'npx playwright test tests/e2e/lobby.spec.ts'
        timeout: 10
        max-score: 4
        
    - name: Navigation Tests
      id: navigation
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Navigation Tests'
        command: 'npx playwright test tests/e2e/navigation.spec.ts'
        timeout: 10
        max-score: 3
        
    - name: Router Tests
      id: router
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Router Tests'
        command: 'npx playwright test tests/e2e/router.spec.ts'
        timeout: 10
        max-score: 2
        
    - name: Rock Paper Scissors Tests
      id: rps-game
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Rock Paper Scissors Tests'
        command: 'npx playwright test tests/e2e/rps.spec.ts'
        timeout: 10
        max-score: 3
        
    - name: Tic-Tac-Toe Tests
      id: tic-tac-toe
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Tic-Tac-Toe Tests'
        command: 'npx playwright test tests/e2e/tic-tac-toe.spec.ts'
        timeout: 10
        max-score: 2
        
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        UNIT-TESTS_RESULTS: "${{steps.unit-tests.outputs.result}}"
        BUILD-TEST_RESULTS: "${{steps.build-test.outputs.result}}"
        APP-INTEGRATION_RESULTS: "${{steps.app-integration.outputs.result}}"
        HOME-PAGE_RESULTS: "${{steps.home-page.outputs.result}}"
        LOBBY-SETTINGS_RESULTS: "${{steps.lobby-settings.outputs.result}}"
        NAVIGATION_RESULTS: "${{steps.navigation.outputs.result}}"
        ROUTER_RESULTS: "${{steps.router.outputs.result}}"
        RPS-GAME_RESULTS: "${{steps.rps-game.outputs.result}}"
        TIC-TAC-TOE_RESULTS: "${{steps.tic-tac-toe.outputs.result}}"
      with:
        runners: unit-tests,build-test,app-integration,home-page,lobby-settings,navigation,router,rps-game,tic-tac-toe
      if: always()